"""more updates to apitokens

Revision ID: 29a4bb085ebd
Revises: bb6503315e8a
Create Date: 2023-12-29 14:13:39.811376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a4bb085ebd'
down_revision = 'bb6503315e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
#        batch_op.drop_constraint('user_id', type_='foreignkey')
        batch_op.drop_column('system_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('system_id', sa.VARCHAR(length=50), nullable=False))
 #       batch_op.create_foreign_key('user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
