"""Salesitems tmp

Revision ID: 364ba146b23e
Revises: b2926dc16796
Create Date: 2023-12-20 17:12:14.943876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364ba146b23e'
down_revision = 'b2926dc16796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.drop_column('vendor_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_name', sa.VARCHAR(length=128), nullable=False))

    # ### end Alembic commands ###
