"""initial migration

Revision ID: 412cc0cdf6d4
Revises: 
Create Date: 2023-12-17 16:49:28.725135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412cc0cdf6d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_base_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sales_margin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('item_purchase_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.drop_column('item_purchase_price')
        batch_op.drop_column('sales_margin')
        batch_op.drop_column('item_base_price')

    # ### end Alembic commands ###
