"""purchase codes added

Revision ID: 4fa5829c72f6
Revises: f70303dc3353
Create Date: 2023-12-19 16:41:16.464334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa5829c72f6'
down_revision = 'f70303dc3353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_code', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.drop_column('purchase_code')

    # ### end Alembic commands ###
