"""fixed constraints on purchases

Revision ID: b2926dc16796
Revises: 4fa5829c72f6
Create Date: 2023-12-19 16:43:48.678766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2926dc16796'
down_revision = '4fa5829c72f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_salesitem_code', type_='unique')
        batch_op.drop_constraint('uq_salesitem_vendor_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_salesitem_vendor_name', ['salesitem_vendor_name'])
        batch_op.create_unique_constraint('uq_salesitem_code', ['salesitem_code'])

    # ### end Alembic commands ###
