"""sales margin removed

Revision ID: bb6503315e8a
Revises: d4071085348c
Create Date: 2023-12-28 20:44:32.645132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6503315e8a'
down_revision = 'd4071085348c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.drop_column('salesitem_sales_margin')

    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.drop_column('sales_margin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_margin', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salesitem_sales_margin', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
