"""connection_name added to apitoken

Revision ID: bbba3767947d
Revises: 29a4bb085ebd
Create Date: 2023-12-29 14:28:53.835127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbba3767947d'
down_revision = '29a4bb085ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_column('connection_name')

    # ### end Alembic commands ###
