"""connection history updates

Revision ID: d4071085348c
Revises: 6040a90c24ab
Create Date: 2023-12-27 18:10:18.066337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4071085348c'
down_revision = '6040a90c24ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updates_received', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updates_sent', sa.Integer(), nullable=True))
        batch_op.alter_column('connection_type',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.Enum('SYNC', 'RESET', name='connectiontype'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.alter_column('connection_type',
               existing_type=sa.Enum('SYNC', 'RESET', name='connectiontype'),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
        batch_op.drop_column('updates_sent')
        batch_op.drop_column('updates_received')

    # ### end Alembic commands ###
