"""sync flag in purchases

Revision ID: e44ac62ede06
Revises: 412cc0cdf6d4
Create Date: 2023-12-18 16:48:34.170104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44ac62ede06'
down_revision = '412cc0cdf6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_sync', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.drop_column('requires_sync')

    # ### end Alembic commands ###
