"""updates to purchase history table

Revision ID: f70303dc3353
Revises: e44ac62ede06
Create Date: 2023-12-19 13:25:02.241078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70303dc3353'
down_revision = 'e44ac62ede06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salesitem_code', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('salesitem_name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('salesitem_vendor_name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('salesitem_item_base_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('salesitem_sales_margin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('salesitem_purchase_price', sa.Float(), nullable=True))
        batch_op.create_unique_constraint('uq_salesitem_vendor_name', ['salesitem_vendor_name'])
        batch_op.create_unique_constraint('uq_salesitem_code', ['salesitem_code'])
        batch_op.drop_column('sales_margin')
        batch_op.drop_column('item_purchase_price')
        batch_op.drop_column('item_base_price')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_base_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('item_purchase_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('sales_margin', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint('uq_salesitem_vendor_name', type_='unique')
        batch_op.drop_constraint('uq_salesitem_code', type_='unique')
        batch_op.drop_column('salesitem_purchase_price')
        batch_op.drop_column('salesitem_sales_margin')
        batch_op.drop_column('salesitem_item_base_price')
        batch_op.drop_column('salesitem_vendor_name')
        batch_op.drop_column('salesitem_name')
        batch_op.drop_column('salesitem_code')
    # ### end Alembic commands ###

    # ### end Alembic commands ###
